import assert from "node:assert/strict";
import { test } from "node:test";
import { readFile } from "node:fs/promises";

test("agent brief is owner-scoped, source-linked, and exportable", async () => {
  const worker = await readFile(new URL("../worker/index.js", import.meta.url), "utf8");
  const mcp = await readFile(new URL("../worker/site-rep-mcp.js", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");

  assert.match(worker, /function buildAgentBrief\(bot, report = buildLaunchReport\(bot\)\)/);
  assert.match(worker, /import \{ handleSiteRepMcp \} from "\.\/site-rep-mcp\.js"/);
  assert.match(worker, /url\.pathname === "\/api\/mcp"/);
  assert.match(worker, /developerApiKeyPrefix: DEVELOPER_API_KEY_PREFIX/);
  assert.match(worker, /recordFailedAuthAttempt/);
  assert.match(mcp, /const MCP_PROTOCOL_VERSION = "2025-06-18"/);
  assert.match(mcp, /"bot:read",\n  "sources:read",\n  "conversations:read",\n  "leads:read"/);
  assert.match(mcp, /export async function handleSiteRepMcp\(request, response, url, deps\)/);
  assert.match(mcp, /message\.method === "initialize"/);
  assert.match(mcp, /message\.method === "tools\/list"/);
  assert.match(mcp, /message\.method === "tools\/call"/);
  assert.match(mcp, /name: "get_site_rep_agent_brief"/);
  assert.match(mcp, /name: "list_site_rep_pending_work"/);
  assert.match(mcp, /name: "get_site_rep_customer_receipt"/);
  assert.match(mcp, /readOnlyHint: true/);
  assert.match(mcp, /destructiveHint: false/);
  assert.match(mcp, /authorizeMcpRequest\(request, deps, SITE_REP_MCP_REQUIRED_SCOPES\)/);
  assert.match(mcp, /developerApiTokenFromRequest\(request\)/);
  assert.match(mcp, /token\.startsWith\(deps\.developerApiKeyPrefix\)/);
  assert.match(mcp, /deps\.normalizeDeveloperApiScopes\(authorizedApiKey\.scopes\)/);
  assert.match(mcp, /deps\.touchDeveloperApiKey\(bot\.botId, authorization\.apiKey\.id\)/);
  assert.match(mcp, /return mcpStructuredToolResult\(deps\.buildAgentBrief\(bot\)\)/);
  assert.match(mcp, /return mcpStructuredToolResult\(deps\.buildSiteRepPendingWork\(bot\)\)/);
  assert.match(mcp, /return mcpStructuredToolResult\(deps\.buildCustomerReceipt\(bot\)\)/);
  assert.match(mcp, /structuredContent/);
  assert.match(mcp, /do not send autonomous outbound messages/);
  assert.match(worker, /url\.pathname === "\/api\/agent-brief"/);
  assert.match(worker, /url\.pathname === "\/api\/export\/agent-brief\.json"/);
  assert.match(worker, /"\/api\/agent-brief"/);
  assert.match(worker, /"\/api\/export\/agent-brief\.json"/);
  assert.match(worker, /mode: "team_review_required"/);
  assert.match(worker, /const conversationTickets = openTickets\.filter\(\(item\) => item\.conversationId\)/);
  assert.match(worker, /const opsTickets = openTickets\.filter\(\(item\) => !item\.conversationId\)/);
  assert.match(worker, /const conversationLeads = leads\.filter\(\(lead\) => lead\.conversationId\)/);
  assert.match(worker, /const sourceGapTickets = conversationTickets\.filter/);
  assert.match(worker, /answerQaGaps = report\.questions\.topGaps/);
  assert.match(worker, /conversationItems: conversationTickets\.slice\(0, 8\)/);
  assert.match(worker, /accountTasks: opsTickets\.slice\(0, 5\)/);
  assert.match(worker, /sourceGaps: sourceGapTickets\.slice\(0, 5\)/);
  assert.match(worker, /answerQaGaps: answerQaGaps\.slice\(0, 5\)/);
  assert.match(worker, /conversationId: item\.conversationId/);
  assert.match(worker, /evidence: "answer_quality_gap"/);
  assert.match(worker, /conversationOnly=1/);
  assert.match(worker, /customerReceiptJson: `\/api\/export\/customer-receipt\.json\?botId=\$\{botId\}`/);
  assert.match(worker, /followUpQueueCsv: `\/api\/export\/follow-up-queue\.csv\?botId=\$\{botId\}&conversationOnly=1`/);
  assert.doesNotMatch(worker, /conversationId: item\.conversationId \|\| null/);
  assert.doesNotMatch(worker, /conversationId: lead\.conversationId \|\| null/);
  assert.doesNotMatch(worker, /proofGaps: report\.questions\.topGaps\.map/);
  assert.doesNotMatch(worker, /ownerQueue: conversationTickets\.slice\(0, 8\)/);
  assert.doesNotMatch(worker, /workspaceProofGaps: /);
  assert.doesNotMatch(worker, /firstCustomerProofJson: /);
  assert.doesNotMatch(worker, /ownerQueueCsv: /);
  assert.match(worker, /Do not claim native helpdesk, CRM sync, compliance certification, or automated external-system execution/);
  assert.doesNotMatch(worker, /buildAgentBrief\(bot\)[\s\S]{0,500}authToken/);
  assert.doesNotMatch(worker, /buildAgentBrief\(bot\)[\s\S]{0,500}webhookUrl/);
  assert.doesNotMatch(mcp, /name: "send_/);
  assert.doesNotMatch(mcp, /name: "approve_/);
  assert.doesNotMatch(mcp, /name: "create_site_rep/);

  assert.match(app, /type AgentBrief = /);
  assert.match(app, /api<AgentBrief \| null>\(`\/api\/agent-brief\?botId=/);
  assert.match(app, /Handoff brief/);
  assert.match(app, /account task/);
  assert.match(app, /answer QA gap/);
  assert.match(app, /activeAgentBrief\.sourceGaps\.length/);
  assert.doesNotMatch(app, /activeAgentBrief\.proofGaps\.length/);
  assert.doesNotMatch(app, /activeAgentBrief\.workspaceProofGaps\.length/);
  assert.match(app, /Export handoff brief/);
  assert.match(app, /siterep-agent-brief\.json/);
  assert.match(styles, /\.agent-brief-strip/);
});
